import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Question from './models/Question.js';

dotenv.config();

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB connected');

    await Question.deleteMany();

    const questions = [
      // ================= WEB DEV =================
      {
        question: 'What does HTML stand for?',
        options: ['Hyper Text Markup Language', 'High Text Machine Language', 'Hyperlinks Text Mark Language', 'Home Tool Markup Language'],
        answer: 'Hyper Text Markup Language',
        category: 'Web Dev',
        difficulty: 'Easy',
      },
      {
        question: 'Which HTML tag is used to create a hyperlink?',
        options: ['<link>', '<a>', '<href>', '<url>'],
        answer: '<a>',
        category: 'Web Dev',
        difficulty: 'Easy',
      },
      {
        question: 'Which CSS property controls text color?',
        options: ['font-style', 'color', 'text-color', 'background-color'],
        answer: 'color',
        category: 'Web Dev',
        difficulty: 'Easy',
      },
      {
        question: 'Which JavaScript keyword is used to declare a constant?',
        options: ['var', 'let', 'const', 'static'],
        answer: 'const',
        category: 'Web Dev',
        difficulty: 'Easy',
      },
      {
        question: 'Which HTTP method is used to fetch data?',
        options: ['POST', 'PUT', 'GET', 'DELETE'],
        answer: 'GET',
        category: 'Web Dev',
        difficulty: 'Easy',
      },

      {
        question: 'Which React hook is used to manage state?',
        options: ['useEffect', 'useState', 'useRef', 'useContext'],
        answer: 'useState',
        category: 'Web Dev',
        difficulty: 'Medium',
      },
      {
        question: 'What is JSX?',
        options: ['JavaScript XML', 'JSON XML', 'Java Syntax Extension', 'JavaScript Extension'],
        answer: 'JavaScript XML',
        category: 'Web Dev',
        difficulty: 'Medium',
      },
      {
        question: 'Which CSS layout system is one-dimensional?',
        options: ['Grid', 'Flexbox', 'Float', 'Position'],
        answer: 'Flexbox',
        category: 'Web Dev',
        difficulty: 'Medium',
      },
      {
        question: 'What does REST stand for?',
        options: ['Representational State Transfer', 'Remote Execution System', 'Random State Transfer', 'Real State Technology'],
        answer: 'Representational State Transfer',
        category: 'Web Dev',
        difficulty: 'Medium',
      },
      {
        question: 'Which status code means "Unauthorized"?',
        options: ['200', '201', '401', '500'],
        answer: '401',
        category: 'Web Dev',
        difficulty: 'Medium',
      },

      {
        question: 'Which database is NoSQL?',
        options: ['MySQL', 'PostgreSQL', 'MongoDB', 'Oracle'],
        answer: 'MongoDB',
        category: 'Web Dev',
        difficulty: 'Hard',
      },
      {
        question: 'JWT is mainly used for?',
        options: ['Encryption', 'Authentication', 'Styling', 'Database'],
        answer: 'Authentication',
        category: 'Web Dev',
        difficulty: 'Hard',
      },
      {
        question: 'Which lifecycle method runs after first render (class component)?',
        options: ['componentWillMount', 'componentDidMount', 'componentWillUpdate', 'render'],
        answer: 'componentDidMount',
        category: 'Web Dev',
        difficulty: 'Hard',
      },
      {
        question: 'Which protocol secures HTTP?',
        options: ['FTP', 'SSL/TLS', 'SSH', 'SMTP'],
        answer: 'SSL/TLS',
        category: 'Web Dev',
        difficulty: 'Hard',
      },
      {
        question: 'Which command initializes a new npm project?',
        options: ['npm start', 'npm install', 'npm init', 'npm build'],
        answer: 'npm init',
        category: 'Web Dev',
        difficulty: 'Hard',
      },
      {
        question: "What does HTML stand for?",
        options: [
          "Hyper Text Markup Language",
          "High Text Machine Language",
          "Hyperlinks Text Mark Language",
          "Home Tool Markup Language",
        ],
        answer: "Hyper Text Markup Language",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which HTML tag is used to create a hyperlink?",
        options: ["<link>", "<a>", "<href>", "<url>"],
        answer: "<a>",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which CSS property controls text color?",
        options: ["font-style", "color", "text-color", "background-color"],
        answer: "color",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which JavaScript keyword declares a variable?",
        options: ["var", "int", "string", "define"],
        answer: "var",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which JavaScript method converts JSON to object?",
        options: [
          "JSON.parse()",
          "JSON.stringify()",
          "JSON.convert()",
          "JSON.object()",
        ],
        answer: "JSON.parse()",
        category: "Web Dev",
        difficulty: "Medium",
      },
      {
        question: "Which company developed React?",
        options: ["Google", "Facebook", "Microsoft", "Amazon"],
        answer: "Facebook",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which React hook runs after render?",
        options: ["useState", "useEffect", "useRef", "useMemo"],
        answer: "useEffect",
        category: "Web Dev",
        difficulty: "Medium",
      },
      {
        question: "Which HTTP status code means Not Found?",
        options: ["200", "404", "500", "301"],
        answer: "404",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: "Which database is NoSQL?",
        options: ["MySQL", "PostgreSQL", "MongoDB", "Oracle"],
        answer: "MongoDB",
        category: "Web Dev",
        difficulty: "Medium",
      },
      {
        question: "Which command installs npm packages?",
        options: ["npm start", "npm install", "npm build", "npm run"],
        answer: "npm install",
        category: "Web Dev",
        difficulty: "Easy",
      },
      {
        question: 'What does HTML stand for?',
        options: ['Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'Home Tool Markup Language'],
        answer: 'Hyper Text Markup Language',
        category: 'Web Development',
        difficulty: 'Easy',
      },
      {
        question: 'Which tag is used to create a hyperlink in HTML?',
        options: ['<link>', '<a>', '<href>', '<url>'],
        answer: '<a>',
        category: 'Web Development',
        difficulty: 'Easy',
      },
      {
        question: 'What does CSS stand for?',
        options: ['Cascading Style Sheets', 'Computer Style Sheets', 'Creative Style System', 'Coded Style Sheets'],
        answer: 'Cascading Style Sheets',
        category: 'Web Development',
        difficulty: 'Easy',
      },
      {
        question: 'Which HTML tag is used for the largest heading?',
        options: ['<h6>', '<heading>', '<h1>', '<head>'],
        answer: '<h1>',
        category: 'Web Development',
        difficulty: 'Easy',
      },
      {
        question: 'Which language is used for styling web pages?',
        options: ['HTML', 'JavaScript', 'CSS', 'Python'],
        answer: 'CSS',
        category: 'Web Development',
        difficulty: 'Easy',
      },
      {
        question: 'Which CSS property is used to change the text color?',
        options: ['font-color', 'text-color', 'color', 'foreground'],
        answer: 'color',
        category: 'Web Development',
        difficulty: 'Medium',
      },
      {
        question: 'What is the correct JavaScript syntax to change the content of an HTML element with id="demo"?',
        options: ['document.getElement("demo").innerHTML = "Hello"', 'document.getElementById("demo").innerHTML = "Hello"', '#demo.innerHTML = "Hello"', 'document.query("demo").text = "Hello"'],
        answer: 'document.getElementById("demo").innerHTML = "Hello"',
        category: 'Web Development',
        difficulty: 'Medium',
      },
      {
        question: 'Which property is used in CSS Flexbox to align items along the main axis?',
        options: ['align-items', 'justify-content', 'align-content', 'flex-direction'],
        answer: 'justify-content',
        category: 'Web Development',
        difficulty: 'Medium',
      },
      {
        question: 'What does API stand for?',
        options: ['Application Programming Interface', 'Applied Program Index', 'Automated Page Integration', 'Application Process Interface'],
        answer: 'Application Programming Interface',
        category: 'Web Development',
        difficulty: 'Medium',
      },
      {
        question: 'Which HTTP method is used to send data to a server to create a resource?',
        options: ['GET', 'PUT', 'POST', 'DELETE'],
        answer: 'POST',
        category: 'Web Development',
        difficulty: 'Medium',
      },
      {
        question: 'What is the purpose of the "async/await" in JavaScript?',
        options: ['To write synchronous code only', 'To handle asynchronous operations more cleanly', 'To speed up loops', 'To declare global variables'],
        answer: 'To handle asynchronous operations more cleanly',
        category: 'Web Development',
        difficulty: 'Hard',
      },
      {
        question: 'What is the Virtual DOM in React?',
        options: ['A direct copy of the browser DOM', 'A lightweight in-memory representation of the real DOM', 'A database for storing UI components', 'A CSS rendering engine'],
        answer: 'A lightweight in-memory representation of the real DOM',
        category: 'Web Development',
        difficulty: 'Hard',
      },
      {
        question: 'Which of the following is NOT a JavaScript framework/library?',
        options: ['React', 'Angular', 'Django', 'Vue'],
        answer: 'Django',
        category: 'Web Development',
        difficulty: 'Hard',
      },
      {
        question: 'What is CORS in web development?',
        options: ['A CSS layout system', 'A security feature that controls cross-origin HTTP requests', 'A type of database query', 'A JavaScript bundler'],
        answer: 'A security feature that controls cross-origin HTTP requests',
        category: 'Web Development',
        difficulty: 'Hard',
      },
      {
        question: 'What is the difference between localStorage and sessionStorage?',
        options: ['localStorage is faster', 'sessionStorage persists after tab closes, localStorage does not', 'localStorage clears when tab closes, sessionStorage persists', 'There is no difference'],
        answer: 'localStorage clears when tab closes, sessionStorage persists',
        category: 'Web Development',
        difficulty: 'Hard',
      },

      // ================= MATH =================
      {
        question: 'What is 15 × 4?',
        options: ['60', '45', '30', '75'],
        answer: '60',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'Square root of 81?',
        options: ['7', '8', '9', '10'],
        answer: '9',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is 20% of 200?',
        options: ['20', '40', '60', '80'],
        answer: '40',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'Value of π (approx)?',
        options: ['3.14', '2.17', '1.41', '4.13'],
        answer: '3.14',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is 7²?',
        options: ['14', '21', '49', '77'],
        answer: '49',
        category: 'Math',
        difficulty: 'Easy',
      },

      {
        question: 'What is the LCM of 4 and 6?',
        options: ['6', '8', '12', '24'],
        answer: '12',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'Solve: 2x + 6 = 14',
        options: ['2', '3', '4', '5'],
        answer: '4',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'Area of rectangle (l=5, b=4)?',
        options: ['9', '18', '20', '25'],
        answer: '20',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'What is 3/4 as decimal?',
        options: ['0.25', '0.5', '0.75', '1.25'],
        answer: '0.75',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: '10³ equals?',
        options: ['30', '100', '1000', '300'],
        answer: '1000',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: "What is 12 × 8?",
        options: ["96", "88", "108", "92"],
        answer: "96",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: "Square root of 144?",
        options: ["10", "11", "12", "13"],
        answer: "12",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: "What is 25% of 200?",
        options: ["25", "50", "75", "100"],
        answer: "50",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: "Value of π (approx)?",
        options: ["3.14", "2.71", "1.61", "3.41"],
        answer: "3.14",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: "Solve: 3x = 18",
        options: ["3", "6", "9", "12"],
        answer: "6",
        category: "Math",
        difficulty: "Medium",
      },
      {
        question: "What is 9²?",
        options: ["18", "27", "81", "99"],
        answer: "81",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: "Area of square (side 6)?",
        options: ["12", "24", "36", "48"],
        answer: "36",
        category: "Math",
        difficulty: "Medium",
      },
      {
        question: "What is 5³?",
        options: ["15", "25", "125", "75"],
        answer: "125",
        category: "Math",
        difficulty: "Medium",
      },
      {
        question: "LCM of 6 and 8?",
        options: ["12", "18", "24", "48"],
        answer: "24",
        category: "Math",
        difficulty: "Medium",
      },
      {
        question: "What is 100 ÷ 4?",
        options: ["20", "25", "30", "40"],
        answer: "25",
        category: "Math",
        difficulty: "Easy",
      },
      {
        question: 'What is 15 + 27?',
        options: ['40', '42', '45', '38'],
        answer: '42',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is 100 ÷ 4?',
        options: ['20', '25', '30', '40'],
        answer: '25',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is the square of 9?',
        options: ['72', '81', '63', '90'],
        answer: '81',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is the value of PI (approx)?',
        options: ['3.12', '3.14', '3.16', '3.18'],
        answer: '3.14',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'How many sides does a hexagon have?',
        options: ['5', '6', '7', '8'],
        answer: '6',
        category: 'Math',
        difficulty: 'Easy',
      },
      {
        question: 'What is the LCM of 6 and 8?',
        options: ['12', '18', '24', '48'],
        answer: '24',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'What is the square root of 144?',
        options: ['11', '12', '13', '14'],
        answer: '12',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'Solve: 3x + 5 = 20. What is x?',
        options: ['3', '4', '5', '6'],
        answer: '5',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'What is 15% of 200?',
        options: ['25', '30', '35', '40'],
        answer: '30',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'What is the area of a circle with radius 7? (π = 22/7)',
        options: ['144', '154', '164', '174'],
        answer: '154',
        category: 'Math',
        difficulty: 'Medium',
      },
      {
        question: 'What is the derivative of x²?',
        options: ['x', '2x', 'x²', '2x²'],
        answer: '2x',
        category: 'Math',
        difficulty: 'Hard',
      },
      {
        question: 'What is log₁₀(1000)?',
        options: ['2', '3', '4', '10'],
        answer: '3',
        category: 'Math',
        difficulty: 'Hard',
      },
      {
        question: 'If a² + b² = 25 and ab = 12, what is (a+b)²?',
        options: ['37', '47', '49', '51'],
        answer: '49',
        category: 'Math',
        difficulty: 'Hard',
      },
      {
        question: 'What is the sum of interior angles of a pentagon?',
        options: ['360°', '450°', '540°', '720°'],
        answer: '540°',
        category: 'Math',
        difficulty: 'Hard',
      },
      {
        question: 'What is the HCF of 36 and 48?',
        options: ['6', '9', '12', '18'],
        answer: '12',
        category: 'Math',
        difficulty: 'Hard',
      },

      // ================= GK =================
      {
        question: 'Capital of India?',
        options: ['Mumbai', 'Delhi', 'Chennai', 'Kolkata'],
        answer: 'Delhi',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'Who is known as Father of the Nation?',
        options: ['Nehru', 'Subhash Bose', 'Gandhi', 'Bhagat Singh'],
        answer: 'Gandhi',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'Largest planet in our solar system?',
        options: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
        answer: 'Jupiter',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'National animal of India?',
        options: ['Lion', 'Elephant', 'Tiger', 'Leopard'],
        answer: 'Tiger',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'How many continents are there?',
        options: ['5', '6', '7', '8'],
        answer: '7',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: "Capital of India?",
        options: ["Mumbai", "Delhi", "Chennai", "Kolkata"],
        answer: "Delhi",
        category: "GK",
        difficulty: "Easy",
      },
      {
        question: "Largest planet in the solar system?",
        options: ["Earth", "Mars", "Jupiter", "Saturn"],
        answer: "Jupiter",
        category: "GK",
        difficulty: "Easy",
      },
      {
        question: "National animal of India?",
        options: ["Lion", "Tiger", "Elephant", "Leopard"],
        answer: "Tiger",
        category: "GK",
        difficulty: "Easy",
      },
      {
        question: "Who invented the telephone?",
        options: [
          "Thomas Edison",
          "Alexander Graham Bell",
          "Nikola Tesla",
          "James Watt",
        ],
        answer: "Alexander Graham Bell",
        category: "GK",
        difficulty: "Medium",
      },
      {
        question: "Which is the longest river in the world?",
        options: ["Amazon", "Nile", "Ganga", "Yangtze"],
        answer: "Nile",
        category: "GK",
        difficulty: "Medium",
      },
      {
        question: "Which country hosted FIFA 2022?",
        options: ["Russia", "Qatar", "Brazil", "USA"],
        answer: "Qatar",
        category: "GK",
        difficulty: "Medium",
      },
      {
        question: "How many states are in India?",
        options: ["28", "29", "30", "27"],
        answer: "28",
        category: "GK",
        difficulty: "Easy",
      },
      {
        question: "Who wrote the Ramayana?",
        options: ["Valmiki", "Kalidas", "Tulsidas", "Vyas"],
        answer: "Valmiki",
        category: "GK",
        difficulty: "Medium",
      },
      {
        question: "Which is the smallest continent?",
        options: ["Europe", "Australia", "Antarctica", "South America"],
        answer: "Australia",
        category: "GK",
        difficulty: "Medium",
      },
      {
        question: "Which gas do plants absorb?",
        options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
        answer: "Carbon Dioxide",
        category: "GK",
        difficulty: "Easy",
      },
      {
        question: 'Which is the longest river in the world?',
        options: ['Amazon', 'Nile', 'Ganga', 'Yangtze'],
        answer: 'Nile',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'Who is known as Father of the Nation of India?',
        options: ['Nehru', 'Subhash Bose', 'Gandhi', 'Bhagat Singh'],
        answer: 'Gandhi',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'What is the capital of Australia?',
        options: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
        answer: 'Canberra',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'How many continents are there on Earth?',
        options: ['5', '6', '7', '8'],
        answer: '7',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'Which planet is known as the Red Planet?',
        options: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
        answer: 'Mars',
        category: 'GK',
        difficulty: 'Easy',
      },
      {
        question: 'Which country hosted FIFA World Cup 2022?',
        options: ['Russia', 'Qatar', 'Brazil', 'USA'],
        answer: 'Qatar',
        category: 'GK',
        difficulty: 'Medium',
      },
      {
        question: 'Who wrote the national anthem of India?',
        options: ['Bankim Chandra', 'Rabindranath Tagore', 'Sarojini Naidu', 'Premchand'],
        answer: 'Rabindranath Tagore',
        category: 'GK',
        difficulty: 'Medium',
      },
      {
        question: 'Which is the smallest continent in the world?',
        options: ['Europe', 'Australia', 'Antarctica', 'South America'],
        answer: 'Australia',
        category: 'GK',
        difficulty: 'Medium',
      },
      {
        question: 'Who wrote the Ramayana?',
        options: ['Valmiki', 'Kalidas', 'Tulsidas', 'Vyas'],
        answer: 'Valmiki',
        category: 'GK',
        difficulty: 'Medium',
      },
      {
        question: 'In which year did India get independence?',
        options: ['1945', '1947', '1950', '1952'],
        answer: '1947',
        category: 'GK',
        difficulty: 'Medium',
      },
      {
        question: 'Which article of Indian Constitution abolished untouchability?',
        options: ['Article 14', 'Article 17', 'Article 21', 'Article 32'],
        answer: 'Article 17',
        category: 'GK',
        difficulty: 'Hard',
      },
      {
        question: 'Who was the first woman Prime Minister of India?',
        options: ['Sarojini Naidu', 'Pratibha Patil', 'Indira Gandhi', 'Sushma Swaraj'],
        answer: 'Indira Gandhi',
        category: 'GK',
        difficulty: 'Hard',
      },
      {
        question: 'Which Indian state has the longest coastline?',
        options: ['Kerala', 'Tamil Nadu', 'Gujarat', 'Andhra Pradesh'],
        answer: 'Gujarat',
        category: 'GK',
        difficulty: 'Hard',
      },
      {
        question: 'The treaty of Versailles was signed in which year?',
        options: ['1917', '1918', '1919', '1920'],
        answer: '1919',
        category: 'GK',
        difficulty: 'Hard',
      },
      {
        question: 'Who invented the telephone?',
        options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'James Watt'],
        answer: 'Alexander Graham Bell',
        category: 'GK',
        difficulty: 'Hard',
      },
    ];

    await Question.insertMany(questions);
    console.log('✅ Genuine questions seeded successfully');
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seed();
